receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # configure jaeger exporter
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed

processors:
  batch:

  transform/extract-span-duration:
    #error_mode: ignore
    trace_statements:
        - context: span
          statements:
            - set(attributes["start_time_unix_nano"], start_time_unix_nano)
            - set(attributes["end_time_unix_nano"], end_time_unix_nano)
            - set(attributes["duration_ms"], (end_time_unix_nano - start_time_unix_nano)/1000)

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, transform/extract-span-duration]
      exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
