receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  influxdb:
    endpoint: 0.0.0.0:8088

exporters:
  # configure jaeger exporter
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
  influxdb:
    endpoint: influxdb:8086
    v1_compatibility:
      enabled: true
      db: inspectit
      username: admin
      password: admin

processors:
  batch:

  transform/extract-span-duration:
    trace_statements:
        - context: span
          statements:
            - set(attributes["start_time_unix_nano"], start_time_unix_nano)
            - set(attributes["end_time_unix_nano"], end_time_unix_nano)
            - set(attributes["duration_ms"], (end_time_unix_nano - start_time_unix_nano)/1000)

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, transform/extract-span-duration]
      exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp, influxdb]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
