services:

  influxdb:
    image: influxdb:2.7.11
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=inspectit
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=inspectit/raw
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - 8085:8086

  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    ports:
      - 8086:8086

#  otelcol:
#    image: otel/opentelemetry-collector-contrib:0.105.0
#    command: ["--config=/etc/otel-collector-config.yaml"]
#    volumes:
#      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
#    ports:
#      - 4317:4317
#      - 4318:4318

  grafana:
    image: grafana/grafana:11.2.0
    attach: false
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
      - GF_SECURITY_ADMIN_PASSWORD=demo
    ports:
      - 3030:3000

  telegraf:
    image: telegraf:1.30.3
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped
    ports:
      - 8084:8086
    depends_on:
      - influx
      - influxdb
