version: '3'
services:
  # Collector for receiving, processing and exporting telemetry data
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: ocelot-dev-otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "9411"        # Zipkin receiver
      - "4317:4317"   # OTLP GRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

  # InfluxDB
  # Time Series Database
  influxdb:
    image: influxdb:1.8
    container_name: ocelot-dev-influxdb
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./influx:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086
    env_file:
      - .env

  #  Jaeger
  ## Collects and visualizes traces
  jaeger:
    image: jaegertracing/all-in-one:1.52.0
    container_name: ocelot-dev-jaeger
    ports:
      - 16686:16686
      - 14268:14268
      - 14250:14250

  #  Grafana
  ## Dashboarding
  grafana:
    image: grafana/grafana:10.2.3
    container_name: ocelot-dev-grafana
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      # Currently, the plugin cannot be found???
      #- GF_INSTALL_PLUGINS=https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/download/v4.0.2/novatec-sdg-panel.zip;novatec-sdg-panel
    volumes:
      - ./grafana/provisioning/influxdb:/usr/share/grafana/custom/
      - ./grafana/provisioning/home-dashboard/home.json:/usr/share/grafana/public/dashboards/home.json
    ports:
      - 3030:3000
    env_file:
      - .env
